# Site settings
title: Amanda Elmore's Notebook
email: agelmore@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Graduate Student  
  University of Michigan 
  Microbiology and Immunology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agelmore.github.io" # the base hostname & protocol for your site
github_username:  agelmore

# Build settings
markdown: kramdown
