# Site settings
title: Amanda Lab Notebook
email: agelmore@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Graduate Student at  
  University of Michigan - 
  Microbiology and Immunology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agelmore.github.io" # the base hostname & protocol for your site
github_username:  agelmore
twitter_username: aelm222

# Build settings
markdown: kramdown
